# Generated by Django 4.1.7 on 2023-03-20 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daycard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='lastposted',
            field=models.DateField(null=True),
        ),
    ]
