# Generated by Django 4.1.7 on 2023-03-06 22:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('daycard', '0002_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='DayCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postTime', models.DateTimeField(auto_now=True)),
                ('wordOne', models.CharField(max_length=20)),
                ('wordTwo', models.CharField(max_length=20)),
                ('wordThree', models.CharField(max_length=20)),
                ('caption', models.CharField(max_length=45)),
                ('colour', models.IntegerField()),
                ('postUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
