# Generated by Django 4.1.7 on 2023-03-07 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('daycard', '0003_daycard'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='daycard',
            options={'verbose_name_plural': 'DayCards'},
        ),
    ]
